# Increase Gradle memory
org.gradle.jvmargs=-Xmx1G

# Fabric / Minecraft setup
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.2
loader_version=0.18.2        # Latest stable 0.18.x for 1.21.11

# Fabric API
fabric_version=0.141.3+1.21.11

# Mod properties
mod_version=0.3.0
maven_group=me.cortex
archives_base_name=nvidium
