name: Build Mod

on:
  push:
    branches: ["main", "port-1.21.11"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nvidium-1.21.11
          path: build/libs/*.jar
